lyoga:
  ball:
    hsv:
      lower: [105, 50, 50]
      upper: [120, 100, 100]
  camera:
    faker_path: fetch/rpi3.lan/faker/runtest
    wb_gains: [1.4144569518716577, 1.7191847593582887]
  hoop:
    center: [159, 81]
    center_dots:
    - [144, 230]
    - [273, 179]
    - [34, 162]
    faker_path: storage/cheat2.png
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    radius: 149
    radius_dots: [5, 5, 5]
  network:
    is_server: true
    serial: {active: false, baud: 9600, com: /dev/serial0}
    server_ip: 127.0.0.1
rpi1:
  ball:
    hsv:
      lower: [ 110, 90, 50 ]
      upper: [ 130, 120, 120 ]
    max_radius: 20
    min_radius: 5
    morph_iterations: 1
  camera:
    wb_gains: [1.4144569518716577, 1.7191847593582887]
  hoop:
    angle_offset: 240
    center: [185, 79]
    center_dots:
    - [247, 206]
    - [105, 191]
    - [318, 125]
    - [45, 84]
    - [314, 28]
    hsv:
      lower: [ 150, 100, 50 ]
      upper: [ 180, 200, 200 ]
    min_radius_dots: 0
    morph_iterations: 0
    radius: 139
    radius_dots: [5, 5, 4, 5, 5]
  network: {is_server: false, server_ip: 192.168.1.103}
rpi2:
  ball:
    hsv:
      lower: [110, 50, 30]
      upper: [130, 150, 120]
    max_radius: 20
    min_radius: 5
    morph_iterations: 1
  camera:
    wb_gains: [1.396570053475936, 1.8325647058823529]
  hoop:
    angle_offset: 120
    center: [159, 87]
    center_dots:
    - [122, 227]
    - [259, 193]
    - [28, 149]
    - [304, 84]
    hsv:
      lower: [160, 100, 50]
      upper: [180, 200, 200]
    radius: 144
    radius_dots: [4, 3, 2, 2]
  network: {is_server: false, server_ip: 192.168.1.103, server_port: 9999}
rpi3:
  ball:
    hsv:
      lower: [110, 90, 50]
      upper: [130, 120, 120]
    max_radius: 20
    min_radius: 5
    morph_iterations: 1
  camera:
    wb_gains: [1.3094716577540109, 1.8870844919786096]
  hoop:
    angle_offset: 0
    center: [143, 80]
    center_dots:
    - [181, 217]
    - [277, 136]
    - [0, 81]
    - [276, 32]
    hsv:
      lower: [150, 100, 50]
      upper: [180, 200, 200]
    min_radius_dots: 0
    morph_iterations: 0
    radius: 142
    radius_dots: [2, 4, 2, 2]
  network:
    is_server: true
    message_bytes: 2
    send_errors: true
    serial: {active: true, baud: 9600, com: /dev/serial0, send_mode: 1}
    server_ip: ''
