lyoga:
  ball:
    hsv:
      lower: [105, 50, 50]
      upper: [120, 100, 100]
  hoop:
    center: [159, 81]
    center_dots:
    - [144, 230]
    - [273, 179]
    - [34, 162]
    faker_path: storage/cheat2.png
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    radius: 149
    radius_dots: [5, 5, 5]
  network:
    is_server: true
    serial: {active: false, baud: 9600, com: /dev/serial0}
    server_ip: 127.0.0.1
    server_port: 9999
  video:
    faker_path: fetch/rpi3.lan/faker/runtest
    wb_gains: [1.4144569518716577, 1.7191847593582887]
rpi1:
  ball:
    hsv:
      lower: [110, 40, 0]
      upper: [150, 100, 75]
  hoop:
    center: [185, 79]
    center_dots:
    - [247, 206]
    - [105, 191]
    - [318, 125]
    - [45, 84]
    - [314, 28]
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    min_radius_dots: 2
    radius: 139
    radius_dots: [5, 5, 4, 5, 5]
  network: {is_server: false, server_ip: 192.168.1.103, server_port: 9999}
  video:
    wb_gains: [1.4144569518716577, 1.7191847593582887]
rpi2:
  ball:
    hsv:
      lower: [110, 50, 30]
      upper: [130, 150, 120]
  hoop:
    center: [159, 87]
    center_dots:
    - [122, 227]
    - [259, 193]
    - [28, 149]
    - [304, 84]
    hsv:
      lower: [160, 100, 50]
      upper: [180, 200, 200]
    radius: 144
    radius_dots: [4, 3, 2, 2]
  network: {is_server: false, server_ip: 192.168.1.103, server_port: 9999}
  video:
    wb_gains: [1.396570053475936, 1.8325647058823529]
rpi3:
  ball:
    hsv:
      lower: [110, 30, 30]
      upper: [130, 120, 120]
  hoop:
    center: [144, 78]
    center_dots:
    - [176, 218]
    - [45, 184]
    - [275, 141]
    - [1, 78]
    hsv:
      lower: [160, 100, 50]
      upper: [180, 200, 200]
    min_radius_dots: 2
    morph_iterations: 1
    radius: 144
    radius_dots: [3, 2, 2, 3]
  network:
    is_server: true
    serial: {active: true, baud: 9600, com: /dev/serial0}
    server_ip: ''
    server_port: 9999
  video:
    wb_gains: [1.43, 1.63]
