all:
  hsv:
    hoop:
      lower:
      - 120
      - 20
      - 20
      upper:
      - 140
      - 255
      - 255
  run_calibration:
    find_hoop: false
    interactive: false
    white_balance: false
rpi1:
  hoop:
    center:
    - 382
    - 136
    center_dots:
    - - 313
      - 429
    - - 577
      - 366
    - - 106
      - 254
    radius: 300
    radius_dots:
    - 10.12432861328125
    - 10.12432861328125
    - 5.147915363311768
  server_ip: localhost
  wb_gains:
  - 1.4144569518716577
  - 1.7191847593582887
rpi2:
  server_ip: 192.168.??
rpi3:
  server_ip: 192.168.??


