lyoga:
  ball:
    hsv:
      lower:
      - 0
      - 150
      - 0
      upper:
      - 30
      - 255
      - 255
  hoop:
    center:
    - 159
    - 81
    center_dots:
    - - 144
      - 230
    - - 273
      - 179
    - - 34
      - 162
    faker_path: storage/cheat2.png
    hsv:
      lower:
      - 45
      - 200
      - 200
      upper:
      - 55
      - 255
      - 255
    radius: 149
    radius_dots:
    - 5
    - 5
    - 5
  network:
    is_server: true
    server_ip: 127.0.0.1
    server_port: 9999
  video:
    faker_path: fetch/rpi2.lan/faker/move/
    wb_gains:
      - 1.4144569518716577
      - 1.7191847593582887
rpi1:
  hoop:
    center:
    - 382
    - 136
    center_dots:
    - - 313
      - 429
    - - 577
      - 366
    - - 106
      - 254
    radius: 300
    radius_dots:
    - 10.12432861328125
    - 10.12432861328125
    - 5.147915363311768
  is_server: true
  server_ip: 127.0.0.1
  wb_gains:
  - 1.4144569518716577
  - 1.7191847593582887
