all:
  run_calibration:
    interactive: false
    white_balance: true
    find_hoop: true

  hsv:
    hoop:
      lower: [150, 20, 20]
      upper: [190, 255, 255]
rpi1:
  server_ip: localhost
rpi2:
  server_ip: 192.168.??
rpi3:
  server_ip: 192.168.??
