all:
  run_calibration:
    next_run:
      color: false
      hoop: true
    every_run: false

  hsv:
    hoop:
      lower: [150, 20, 20]
      upper: [190, 255, 255]
rpi1:
  server_ip: localhost
rpi2:
  server_ip: 192.168.??
rpi3:
  server_ip: 192.168.??
