lyoga:
  ball:
    hsv:
      lower: [0, 150, 0]
      upper: [30, 255, 255]
  hoop:
    center: [159, 81]
    center_dots:
    - [144, 230]
    - [273, 179]
    - [34, 162]
    faker_path: storage/cheat2.png
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    radius: 149
    radius_dots: [5, 5, 5]
  network: {is_server: true, server_ip: 127.0.0.1, server_port: 9999}
  video:
    faker_path: fetch/rpi2.lan/faker/move/
    wb_gains: [1.4144569518716577, 1.7191847593582887]
rpi1:
  ball:
    hsv:
      lower: [0, 150, 0]
      upper: [30, 255, 255]
  hoop:
    center: [185, 79]
    center_dots:
    - [247, 206]
    - [105, 191]
    - [318, 125]
    - [45, 84]
    - [314, 28]
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    radius: 139
    radius_dots: [5, 5, 4, 5, 5]
  network: {server_ip: rpi3.lan, server_port: 9999, is_server: false}
  video:
    wb_gains: [1.4144569518716577, 1.7191847593582887]
rpi2:
  ball:
    hsv:
      lower: [0, 150, 0]
      upper: [30, 255, 255]
  hoop:
    center: [159, 81]
    center_dots:
    - [144, 230]
    - [273, 179]
    - [34, 162]
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    radius: 149
    radius_dots: [5, 5, 5]
  network: {server_ip: rpi3.lan, server_port: 9999, is_server: false}
  video:
    wb_gains: [1.4144569518716577, 1.7191847593582887]
rpi3:
  ball:
    hsv:
      lower: [0, 150, 0]
      upper: [30, 255, 255]
  hoop:
    center: [144, 81]
    center_dots:
    - [163, 221]
    - [36, 174]
    - [272, 150]
    - [2, 68]
    - [280, 43]
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    radius: 142
    radius_dots: [5, 5, 5, 5, 5]
  network: {is_server: true, server_ip: rpi3.lan, server_port: 9999}
  video:
    wb_gains: [1.4144569518716577, 1.7191847593582887]
