rpi1:
  hoop:
    center:
    - 382
    - 136
    center_dots:
    - - 313
      - 429
    - - 577
      - 366
    - - 106
      - 254
    radius: 300
    radius_dots:
    - 10.12432861328125
    - 10.12432861328125
    - 5.147915363311768
  is_server: true
  server_ip: 127.0.0.1
  wb_gains:
  - 1.4144569518716577
  - 1.7191847593582887

lyoga:
  video:
    faker_path: fetch/rpi1.lan/faker/test/
  hoop:
    faker_path:
    center: [50, 50]
    center_dots:
    radius: 100
    radius_dots:
  ball:
    hsv:
      lower: [0, 0, 0]
      upper: [255, 255, 255]
  network:
