lyoga:
  ball:
    hsv:
      lower: [105, 50, 50]
      upper: [120, 100, 100]
  hoop:
    center: [159, 81]
    center_dots:
    - [144, 230]
    - [273, 179]
    - [34, 162]
    faker_path: storage/cheat2.png
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    radius: 149
    radius_dots: [5, 5, 5]
  network: {is_server: true, server_ip: 127.0.0.1, server_port: 9999, use_serial: false}
  video:
    faker_path: fetch/rpi3.lan/faker/runtest
    wb_gains: [1.4144569518716577, 1.7191847593582887]
rpi1:
  ball:
    hsv:
      lower: [110, 40, 0]
      upper: [150, 100, 75]
  hoop:
    center: [185, 79]
    center_dots:
    - [247, 206]
    - [105, 191]
    - [318, 125]
    - [45, 84]
    - [314, 28]
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    radius: 139
    radius_dots: [5, 5, 4, 5, 5]
  network: {is_server: false, server_ip: 192.168.1.103, server_port: 9999}
  video:
    wb_gains: [1.4144569518716577, 1.7191847593582887]
rpi2:
  ball:
    hsv:
      lower: [110, 40, 0]
      upper: [150, 100, 75]
  hoop:
    center: [159, 81]
    center_dots:
    - [144, 230]
    - [273, 179]
    - [34, 162]
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    radius: 149
    radius_dots: [5, 5, 5]
  network: {is_server: false, server_ip: 192.168.1.103, server_port: 9999}
  video:
    wb_gains: [1.4144569518716577, 1.7191847593582887]
rpi3:
  ball:
    hsv:
      lower: [105, 50, 50]
      upper: [120, 100, 100]
  hoop:
    center: [144, 81]
    center_dots:
    - [163, 221]
    - [36, 174]
    - [272, 150]
    - [2, 68]
    - [280, 43]
    hsv:
      lower: [45, 200, 200]
      upper: [55, 255, 255]
    radius: 142
    radius_dots: [5, 5, 5, 5, 5]
    min_radius_dots: 2
    morph_iterations: 1
  network: {is_server: true, server_ip: '', server_port: 9999}
  video:
    wb_gains: [1.43, 1.63]
