#- name: setup and update the pis
#  import_playbook: setupRPi.yml
- hosts: rpi
  vars:
    cmd: "--vid top 180 60 1"
  tasks:
  - name: Execute command
    command:
      cmd: "python3 debug.py {{ cmd }}"
      chdir: "~/ball-and-hoop/"

- name: sync stuff back
  import_playbook: pull-storage.yml
