rpi:
  hosts:
    rpi1.lan:
    rpi2.lan:
    rpi3.lan:
       ansible_ssh_host: fd06:f558:c7d8::588
  vars:
    ansible_ssh_user: pi
    ansible_ssh_password: raspberry
    ansible_python_interpreter: /usr/bin/python3
