- hosts: rpi
  tasks:
  - name: Install needed system packages
    package:
      name:
        - git
        - python3
        - python3-opencv
        - python3-picamera
        #  https://stackoverflow.com/questions/53347759/importerror-libcblas-so-3-cannot-open-shared-object-file-no-such-file-or-dire
        - libatlas-base-dev
        - libjasper-dev
    become: yes

  - name: install this repo on remote host
    git:
      repo: https://github.com/lukas-staab/ball-and-hoop.git
      dest: ~/ball-and-hoop
      clone: yes
      version: master

  - name: Install pip requirements
    pip:
      requirements: ~/ball-and-hoop/requirements.txt
      executable: pip3