- hosts: rpi
  tasks:
    - name: Install needed system packages
      package:
        name:
          - git
          - python3
          - python3-opencv
          - python3-picamera

    - name: install this repo on remote host
      git:
        repo: git@github.com:lukas-staab/ball-and-hoop.git
        dest: ~/ball-and-hoop
        clone: yes
        version: master

    - name: Install pip requirements
      pip:
        name:
          - pyserial
    - name: