# This is a basic workflow to help you get started with Actions

name: deploy Sphinx to github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # checks out git repo
    - uses: actions/setup-python@v4 # installing python and pip
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme
    - name: Sphinx build
      run: |
        sphinx-build docs/source docs/build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        force_orphan: true